
package com.amadeus.xml;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.amadeus.wsdl._2010._06.ws.link_v1.TransactionFlowLinkType;
import com.amadeus.xml._2010._06.security_v1.AMASecurityHostedUser;
import com.amadeus.xml._2010._06.session_v3.Session;
import com.amadeus.xml.fmptbq_14_2_1a.AttributeType;
import com.amadeus.xml.fmptbq_14_2_1a.ConsumerReferenceInformationType;
import com.amadeus.xml.fmptbq_14_2_1a.FOPRepresentationType;
import com.amadeus.xml.fmptbq_14_2_1a.GroupPassengerDetailsType;
import com.amadeus.xml.fmptbq_14_2_1a.NumberOfUnitsType;
import com.amadeus.xml.fmptbq_14_2_1a.TaxType;
import com.amadeus.xml.fmptbq_14_2_1a.TravelFlightInformationType165052S;
import com.amadeus.xml.fmptbq_14_2_1a.TravellerReferenceInformationType;
import com.amadeus.xml.fmptbr_14_2_1a.CompanyIdentificationTextType;
import com.amadeus.xml.fmptbr_14_2_1a.FareFamilyType;
import com.amadeus.xml.fmptbr_14_2_1a.StatusType;
import com.amadeus.xml.pnracc_14_1_1a.InteractiveFreeTextTypeI132924S;
import com.amadeus.xml.pnracc_14_1_1a.LongFreeTextType;
import com.amadeus.xml.pnracc_14_1_1a.NumberOfUnitsTypeI;
import com.amadeus.xml.pnracc_14_1_1a.POSGroupType;
import com.amadeus.xml.pnracc_14_1_1a.PnrHistoryDataType;
import com.amadeus.xml.pnracc_14_1_1a.QueueType;
import com.amadeus.xml.pnracc_14_1_1a.ReservationSecurityInformationType156156S;
import com.amadeus.xml.pnracc_14_1_1a.SegmentGroupingInformationType;
import com.amadeus.xml.pnracc_14_1_1a.StatusType178422S;
import com.amadeus.xml.pnrret_14_1_1a.PNRRetrieve;
import com.amadeus.xml.pnrspl_14_1_1a.SplitPNRType;
import com.amadeus.xml.pnrxcl_14_1_1a.CancelPNRElementType;
import com.amadeus.xml.smpreq_13_1_ia.AdditionalBusinessSourceInformationTypeI;
import com.amadeus.xml.smpreq_13_1_ia.EquipmentInfoTypeI;
import com.amadeus.xml.smpreq_13_1_ia.FrequentTravellerInformationTypeI;
import com.amadeus.xml.smpreq_13_1_ia.RelatedProductInformationTypeI;
import com.amadeus.xml.smpreq_13_1_ia.TravelProductInformationTypeI;
import com.amadeus.xml.smpres_13_1_ia.ErrorInformationTypeI;
import com.amadeus.xml.smpres_13_1_ia.ResponseAnalysisDetailsTypeI;
import com.amadeus.xml.smpres_13_1_ia.WarningInformationTypeI;
import com.amadeus.xml.tipnrq_12_4_1a.CorporateFareInformationType;
import com.amadeus.xml.tipnrq_12_4_1a.FormOfPaymentTypeI;
import com.amadeus.xml.tnlres_00_1_1a.PNRList;
import com.amadeus.xml.tpcbrq_12_4_1a.CommercialAgreementsTypeI;
import com.amadeus.xml.tpcbrq_12_4_1a.DutyTaxFeeDetailsTypeU;
import com.amadeus.xml.tpcbrq_12_4_1a.PointOfSaleInformationTypeU;
import com.amadeus.xml.tpcbrq_12_4_1a.ReferenceInformationTypeI94605S;
import com.amadeus.xml.tpcbrq_12_4_1a.TransportIdentifierType;
import com.amadeus.xml.ttktiq_09_1_1a.ReferenceInfoType;
import com.amadeus.xml.ttktiq_09_1_1a.ReferenceInformationType;
import com.amadeus.xml.ttktiq_09_1_1a.StockInformationType;
import com.amadeus.xml.ttktiq_09_1_1a.TicketAgentInfoTypeI;
import com.amadeus.xml.ttktiq_09_1_1a.TravellerInformationType;
import com.amadeus.xml.vlssoq_04_1_1a.ConversationIDType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AmadeusWebServicesPT", targetNamespace = "http://xml.amadeus.com")
@XmlSeeAlso({
    com.amadeus.xml._2010._06.security_v1.ObjectFactory.class,
    com.amadeus.xml.farqnq_07_1_1a.ObjectFactory.class,
    com.amadeus.xml.farqnr_07_1_1a.ObjectFactory.class,
    com.amadeus.xml.fmptbq_14_2_1a.ObjectFactory.class,
    com.amadeus.xml.fmptbr_14_2_1a.ObjectFactory.class,
    com.amadeus.xml.itareq_05_2_ia.ObjectFactory.class,
    com.amadeus.xml.itares_05_2_ia.ObjectFactory.class,
    com.amadeus.xml.pnracc_14_1_1a.ObjectFactory.class,
    com.amadeus.xml.pnradd_14_1_1a.ObjectFactory.class,
    com.amadeus.xml.pnrret_14_1_1a.ObjectFactory.class,
    com.amadeus.xml.smpreq_13_1_ia.ObjectFactory.class,
    com.amadeus.xml.smpres_13_1_ia.ObjectFactory.class,
    com.amadeus.xml.tautcq_04_1_1a.ObjectFactory.class,
    com.amadeus.xml.tautcr_04_1_1a.ObjectFactory.class,
    com.amadeus.xml.tipnrq_12_4_1a.ObjectFactory.class,
    com.amadeus.xml.tipnrr_12_4_1a.ObjectFactory.class,
    com.amadeus.xml.tnlres_00_1_1a.ObjectFactory.class,
    com.amadeus.xml.tpcbrq_12_4_1a.ObjectFactory.class,
    com.amadeus.xml.tpcbrr_12_4_1a.ObjectFactory.class,
    com.amadeus.xml.ttktiq_09_1_1a.ObjectFactory.class,
    com.amadeus.xml.vlssor_04_1_1a.ObjectFactory.class,
    org.iata.iata._2007._00.iata2010.ObjectFactory.class,
    org.opentravel.ota._2003._05.ota2010b.ObjectFactory.class,
    com.amadeus.xml._2010._06.types_v1.ObjectFactory.class,
    com.amadeus.xml._2010._06.appmdw_commontypes_v3.ObjectFactory.class,
    com.amadeus.wsdl._2010._06.ws.link_v1.ObjectFactory.class,
    com.amadeus.xml._2010._06.session_v3.ObjectFactory.class,
    com.amadeus.xml.pnrspl_14_1_1a.ObjectFactory.class,
    com.amadeus.xml.pnrxcl_14_1_1a.ObjectFactory.class,
    com.amadeus.xml.ttktir_09_1_1a.ObjectFactory.class,
    com.amadeus.xml.vlssoq_04_1_1a.ObjectFactory.class
})
public interface AmadeusWebServicesPT {


    /**
     * 
     * @param seatRequestParameters
     * @param responseDetails
     * @param seatmapInformation
     * @param seatRequestParameters0
     * @param link
     * @param errorInformation
     * @param productInformation
     * @param equipmentInformation
     * @param traveler
     * @param security
     * @param frequentTravelerInfo
     * @param resControlInfo
     * @param additionalInfo
     * @param travelProductIdent
     * @param warningInformation
     * @param session
     * @param conversionRate
     */
    @WebMethod(operationName = "Air_RetrieveSeatMap", action = "http://webservices.amadeus.com/SMPREQ_13_1_IA")
    @RequestWrapper(localName = "Air_RetrieveSeatMap", targetNamespace = "http://xml.amadeus.com/SMPREQ_13_1_IA", className = "com.amadeus.xml.smpreq_13_1_ia.AirRetrieveSeatMap")
    @ResponseWrapper(localName = "Air_RetrieveSeatMapReply", targetNamespace = "http://xml.amadeus.com/SMPRES_13_1_IA", className = "com.amadeus.xml.smpres_13_1_ia.AirRetrieveSeatMapReply")
    public void airRetrieveSeatMap(
        @WebParam(name = "travelProductIdent", targetNamespace = "http://xml.amadeus.com/SMPREQ_13_1_IA")
        TravelProductInformationTypeI travelProductIdent,
        @WebParam(name = "seatRequestParameters", targetNamespace = "http://xml.amadeus.com/SMPREQ_13_1_IA")
        com.amadeus.xml.smpreq_13_1_ia.SeatRequestParametersTypeI seatRequestParameters,
        @WebParam(name = "productInformation", targetNamespace = "http://xml.amadeus.com/SMPREQ_13_1_IA")
        RelatedProductInformationTypeI productInformation,
        @WebParam(name = "frequentTravelerInfo", targetNamespace = "http://xml.amadeus.com/SMPREQ_13_1_IA")
        FrequentTravellerInformationTypeI frequentTravelerInfo,
        @WebParam(name = "resControlInfo", targetNamespace = "http://xml.amadeus.com/SMPREQ_13_1_IA")
        com.amadeus.xml.smpreq_13_1_ia.ReservationControlInformationTypeI resControlInfo,
        @WebParam(name = "equipmentInformation", targetNamespace = "http://xml.amadeus.com/SMPREQ_13_1_IA")
        EquipmentInfoTypeI equipmentInformation,
        @WebParam(name = "additionalInfo", targetNamespace = "http://xml.amadeus.com/SMPREQ_13_1_IA")
        AdditionalBusinessSourceInformationTypeI additionalInfo,
        @WebParam(name = "conversionRate", targetNamespace = "http://xml.amadeus.com/SMPREQ_13_1_IA")
        com.amadeus.xml.smpreq_13_1_ia.ConversionRateTypeI conversionRate,
        @WebParam(name = "traveler", targetNamespace = "http://xml.amadeus.com/SMPREQ_13_1_IA")
        List<com.amadeus.xml.smpreq_13_1_ia.AirRetrieveSeatMap.Traveler> traveler,
        @WebParam(name = "responseDetails", targetNamespace = "http://xml.amadeus.com/SMPRES_13_1_IA", mode = WebParam.Mode.OUT)
        Holder<ResponseAnalysisDetailsTypeI> responseDetails,
        @WebParam(name = "errorInformation", targetNamespace = "http://xml.amadeus.com/SMPRES_13_1_IA", mode = WebParam.Mode.OUT)
        Holder<ErrorInformationTypeI> errorInformation,
        @WebParam(name = "warningInformation", targetNamespace = "http://xml.amadeus.com/SMPRES_13_1_IA", mode = WebParam.Mode.OUT)
        Holder<WarningInformationTypeI> warningInformation,
        @WebParam(name = "seatRequestParameters", targetNamespace = "http://xml.amadeus.com/SMPRES_13_1_IA", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.smpres_13_1_ia.SeatRequestParametersTypeI> seatRequestParameters0,
        @WebParam(name = "seatmapInformation", targetNamespace = "http://xml.amadeus.com/SMPRES_13_1_IA", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.smpres_13_1_ia.AirRetrieveSeatMapReply.SeatmapInformation>> seatmapInformation,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param message
     * @param recordLocator
     * @param messageActionDetails
     * @param session
     * @param itineraryDetails
     * @param link
     * @param itineraryDetails0
     * @param security
     * @param errorAtMessageLevel
     */
    @WebMethod(operationName = "Air_SellFromRecommendation", action = "http://webservices.amadeus.com/ITAREQ_05_2_IA")
    @RequestWrapper(localName = "Air_SellFromRecommendation", targetNamespace = "http://xml.amadeus.com/ITAREQ_05_2_IA", className = "com.amadeus.xml.itareq_05_2_ia.AirSellFromRecommendation")
    @ResponseWrapper(localName = "Air_SellFromRecommendationReply", targetNamespace = "http://xml.amadeus.com/ITARES_05_2_IA", className = "com.amadeus.xml.itares_05_2_ia.AirSellFromRecommendationReply")
    public void airSellFromRecommendation(
        @WebParam(name = "messageActionDetails", targetNamespace = "http://xml.amadeus.com/ITAREQ_05_2_IA")
        com.amadeus.xml.itareq_05_2_ia.MessageActionDetailsTypeI messageActionDetails,
        @WebParam(name = "recordLocator", targetNamespace = "http://xml.amadeus.com/ITAREQ_05_2_IA")
        com.amadeus.xml.itareq_05_2_ia.ReservationControlInformationTypeI recordLocator,
        @WebParam(name = "itineraryDetails", targetNamespace = "http://xml.amadeus.com/ITAREQ_05_2_IA")
        List<com.amadeus.xml.itareq_05_2_ia.AirSellFromRecommendation.ItineraryDetails> itineraryDetails,
        @WebParam(name = "message", targetNamespace = "http://xml.amadeus.com/ITARES_05_2_IA", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.itares_05_2_ia.MessageActionDetailsTypeI> message,
        @WebParam(name = "errorAtMessageLevel", targetNamespace = "http://xml.amadeus.com/ITARES_05_2_IA", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.itares_05_2_ia.AirSellFromRecommendationReply.ErrorAtMessageLevel>> errorAtMessageLevel,
        @WebParam(name = "itineraryDetails", targetNamespace = "http://xml.amadeus.com/ITARES_05_2_IA", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.itares_05_2_ia.AirSellFromRecommendationReply.ItineraryDetails>> itineraryDetails0,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param link
     * @param paxSelection
     * @param security
     * @param selection
     * @param otherCompoundOptions
     * @param agentInfo
     * @param stock
     * @param optionGroup
     * @param processingStatus
     * @param session
     * @param overrideDate
     * @param errorGroup
     * @param infantOrAdultAssociation
     */
    @WebMethod(operationName = "DocIssuance_IssueTicket", action = "http://webservices.amadeus.com/TTKTIQ_09_1_1A")
    @RequestWrapper(localName = "DocIssuance_IssueTicket", targetNamespace = "http://xml.amadeus.com/TTKTIQ_09_1_1A", className = "com.amadeus.xml.ttktiq_09_1_1a.DocIssuanceIssueTicket")
    @ResponseWrapper(localName = "DocIssuance_IssueTicketReply", targetNamespace = "http://xml.amadeus.com/TTKTIR_09_1_1A", className = "com.amadeus.xml.ttktir_09_1_1a.DocIssuanceIssueTicketReply")
    public void docIssuanceIssueTicket(
        @WebParam(name = "agentInfo", targetNamespace = "http://xml.amadeus.com/TTKTIQ_09_1_1A")
        TicketAgentInfoTypeI agentInfo,
        @WebParam(name = "overrideDate", targetNamespace = "http://xml.amadeus.com/TTKTIQ_09_1_1A")
        com.amadeus.xml.ttktiq_09_1_1a.StructuredDateTimeInformationType overrideDate,
        @WebParam(name = "selection", targetNamespace = "http://xml.amadeus.com/TTKTIQ_09_1_1A")
        List<ReferenceInfoType> selection,
        @WebParam(name = "paxSelection", targetNamespace = "http://xml.amadeus.com/TTKTIQ_09_1_1A")
        List<ReferenceInformationType> paxSelection,
        @WebParam(name = "stock", targetNamespace = "http://xml.amadeus.com/TTKTIQ_09_1_1A")
        StockInformationType stock,
        @WebParam(name = "optionGroup", targetNamespace = "http://xml.amadeus.com/TTKTIQ_09_1_1A")
        List<com.amadeus.xml.ttktiq_09_1_1a.DocIssuanceIssueTicket.OptionGroup> optionGroup,
        @WebParam(name = "infantOrAdultAssociation", targetNamespace = "http://xml.amadeus.com/TTKTIQ_09_1_1A")
        TravellerInformationType infantOrAdultAssociation,
        @WebParam(name = "otherCompoundOptions", targetNamespace = "http://xml.amadeus.com/TTKTIQ_09_1_1A")
        List<com.amadeus.xml.ttktiq_09_1_1a.CodedAttributeType> otherCompoundOptions,
        @WebParam(name = "processingStatus", targetNamespace = "http://xml.amadeus.com/TTKTIR_09_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.ttktir_09_1_1a.ResponseAnalysisDetailsType> processingStatus,
        @WebParam(name = "errorGroup", targetNamespace = "http://xml.amadeus.com/TTKTIR_09_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.ttktir_09_1_1a.ErrorGroupType> errorGroup,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param infoText
     * @param fareRouteInfo
     * @param errorInfo
     * @param transportInformation
     * @param link
     * @param security
     * @param dateOfFlight
     * @param statusInfo
     * @param tripDescription
     * @param tariffInfo
     * @param fareRule
     * @param pricingTickInfo
     * @param transactionType
     * @param availcabinStatus
     * @param flightQualification
     * @param session
     * @param msgType
     * @param itemNumber
     * @param multiCorporate
     * @param flightDetails
     * @param conversionRate
     * @param pricingInfo
     */
    @WebMethod(operationName = "Fare_CheckRules", action = "http://webservices.amadeus.com/FARQNQ_07_1_1A")
    @RequestWrapper(localName = "Fare_CheckRules", targetNamespace = "http://xml.amadeus.com/FARQNQ_07_1_1A", className = "com.amadeus.xml.farqnq_07_1_1a.FareCheckRules")
    @ResponseWrapper(localName = "Fare_CheckRulesReply", targetNamespace = "http://xml.amadeus.com/FARQNR_07_1_1A", className = "com.amadeus.xml.farqnr_07_1_1a.FareCheckRulesReply")
    public void fareCheckRules(
        @WebParam(name = "msgType", targetNamespace = "http://xml.amadeus.com/FARQNQ_07_1_1A")
        com.amadeus.xml.farqnq_07_1_1a.FareCheckRules.MsgType msgType,
        @WebParam(name = "availcabinStatus", targetNamespace = "http://xml.amadeus.com/FARQNQ_07_1_1A")
        com.amadeus.xml.farqnq_07_1_1a.FareCheckRules.AvailcabinStatus availcabinStatus,
        @WebParam(name = "conversionRate", targetNamespace = "http://xml.amadeus.com/FARQNQ_07_1_1A")
        com.amadeus.xml.farqnq_07_1_1a.FareCheckRules.ConversionRate conversionRate,
        @WebParam(name = "pricingTickInfo", targetNamespace = "http://xml.amadeus.com/FARQNQ_07_1_1A")
        com.amadeus.xml.farqnq_07_1_1a.FareCheckRules.PricingTickInfo pricingTickInfo,
        @WebParam(name = "multiCorporate", targetNamespace = "http://xml.amadeus.com/FARQNQ_07_1_1A")
        com.amadeus.xml.farqnq_07_1_1a.FareCheckRules.MultiCorporate multiCorporate,
        @WebParam(name = "itemNumber", targetNamespace = "http://xml.amadeus.com/FARQNQ_07_1_1A")
        com.amadeus.xml.farqnq_07_1_1a.FareCheckRules.ItemNumber itemNumber,
        @WebParam(name = "dateOfFlight", targetNamespace = "http://xml.amadeus.com/FARQNQ_07_1_1A")
        com.amadeus.xml.farqnq_07_1_1a.FareCheckRules.DateOfFlight dateOfFlight,
        @WebParam(name = "flightQualification", targetNamespace = "http://xml.amadeus.com/FARQNQ_07_1_1A")
        List<com.amadeus.xml.farqnq_07_1_1a.FareCheckRules.FlightQualification> flightQualification,
        @WebParam(name = "transportInformation", targetNamespace = "http://xml.amadeus.com/FARQNQ_07_1_1A")
        List<com.amadeus.xml.farqnq_07_1_1a.FareCheckRules.TransportInformation> transportInformation,
        @WebParam(name = "tripDescription", targetNamespace = "http://xml.amadeus.com/FARQNQ_07_1_1A")
        List<com.amadeus.xml.farqnq_07_1_1a.FareCheckRules.TripDescription> tripDescription,
        @WebParam(name = "pricingInfo", targetNamespace = "http://xml.amadeus.com/FARQNQ_07_1_1A")
        List<com.amadeus.xml.farqnq_07_1_1a.FareCheckRules.PricingInfo> pricingInfo,
        @WebParam(name = "fareRule", targetNamespace = "http://xml.amadeus.com/FARQNQ_07_1_1A")
        com.amadeus.xml.farqnq_07_1_1a.FareCheckRules.FareRule fareRule,
        @WebParam(name = "transactionType", targetNamespace = "http://xml.amadeus.com/FARQNR_07_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.farqnr_07_1_1a.FareCheckRulesReply.TransactionType> transactionType,
        @WebParam(name = "statusInfo", targetNamespace = "http://xml.amadeus.com/FARQNR_07_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.farqnr_07_1_1a.FareCheckRulesReply.StatusInfo> statusInfo,
        @WebParam(name = "fareRouteInfo", targetNamespace = "http://xml.amadeus.com/FARQNR_07_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.farqnr_07_1_1a.FareCheckRulesReply.FareRouteInfo> fareRouteInfo,
        @WebParam(name = "infoText", targetNamespace = "http://xml.amadeus.com/FARQNR_07_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.farqnr_07_1_1a.FareCheckRulesReply.InfoText>> infoText,
        @WebParam(name = "errorInfo", targetNamespace = "http://xml.amadeus.com/FARQNR_07_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.farqnr_07_1_1a.FareCheckRulesReply.ErrorInfo> errorInfo,
        @WebParam(name = "tariffInfo", targetNamespace = "http://xml.amadeus.com/FARQNR_07_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.farqnr_07_1_1a.FareCheckRulesReply.TariffInfo>> tariffInfo,
        @WebParam(name = "flightDetails", targetNamespace = "http://xml.amadeus.com/FARQNR_07_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.farqnr_07_1_1a.FareCheckRulesReply.FlightDetails>> flightDetails,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param link
     * @param instantPricingOption
     * @param corporateFares
     * @param security
     * @param passengersGroup
     * @param messageDetails
     * @param tripsGroup
     * @param originatorGroup
     * @param messageDetails0
     * @param generalFormOfPayment
     * @param pricingOptionsGroup
     * @param taxExemptGroup
     * @param session
     * @param currencyOverride
     * @param mainGroup
     * @param errorGroup
     * @param obFeeRequestGroup
     */
    @WebMethod(operationName = "Fare_InformativePricingWithoutPNR", action = "http://webservices.amadeus.com/TIPNRQ_12_4_1A")
    @RequestWrapper(localName = "Fare_InformativePricingWithoutPNR", targetNamespace = "http://xml.amadeus.com/TIPNRQ_12_4_1A", className = "com.amadeus.xml.tipnrq_12_4_1a.FareInformativePricingWithoutPNR")
    @ResponseWrapper(localName = "Fare_InformativePricingWithoutPNRReply", targetNamespace = "http://xml.amadeus.com/TIPNRR_12_4_1A", className = "com.amadeus.xml.tipnrr_12_4_1a.FareInformativePricingWithoutPNRReply")
    public void fareInformativePricingWithoutPNR(
        @WebParam(name = "messageDetails", targetNamespace = "http://xml.amadeus.com/TIPNRQ_12_4_1A")
        com.amadeus.xml.tipnrq_12_4_1a.MessageActionDetailsTypeI messageDetails,
        @WebParam(name = "originatorGroup", targetNamespace = "http://xml.amadeus.com/TIPNRQ_12_4_1A")
        com.amadeus.xml.tipnrq_12_4_1a.FareInformativePricingWithoutPNR.OriginatorGroup originatorGroup,
        @WebParam(name = "currencyOverride", targetNamespace = "http://xml.amadeus.com/TIPNRQ_12_4_1A")
        com.amadeus.xml.tipnrq_12_4_1a.ConversionRateTypeI currencyOverride,
        @WebParam(name = "corporateFares", targetNamespace = "http://xml.amadeus.com/TIPNRQ_12_4_1A")
        CorporateFareInformationType corporateFares,
        @WebParam(name = "taxExemptGroup", targetNamespace = "http://xml.amadeus.com/TIPNRQ_12_4_1A")
        com.amadeus.xml.tipnrq_12_4_1a.FareInformativePricingWithoutPNR.TaxExemptGroup taxExemptGroup,
        @WebParam(name = "generalFormOfPayment", targetNamespace = "http://xml.amadeus.com/TIPNRQ_12_4_1A")
        FormOfPaymentTypeI generalFormOfPayment,
        @WebParam(name = "passengersGroup", targetNamespace = "http://xml.amadeus.com/TIPNRQ_12_4_1A")
        List<com.amadeus.xml.tipnrq_12_4_1a.FareInformativePricingWithoutPNR.PassengersGroup> passengersGroup,
        @WebParam(name = "pricingOptionsGroup", targetNamespace = "http://xml.amadeus.com/TIPNRQ_12_4_1A")
        List<com.amadeus.xml.tipnrq_12_4_1a.FareInformativePricingWithoutPNR.PricingOptionsGroup> pricingOptionsGroup,
        @WebParam(name = "instantPricingOption", targetNamespace = "http://xml.amadeus.com/TIPNRQ_12_4_1A")
        com.amadeus.xml.tipnrq_12_4_1a.MonetaryInformationType instantPricingOption,
        @WebParam(name = "tripsGroup", targetNamespace = "http://xml.amadeus.com/TIPNRQ_12_4_1A")
        com.amadeus.xml.tipnrq_12_4_1a.FareInformativePricingWithoutPNR.TripsGroup tripsGroup,
        @WebParam(name = "obFeeRequestGroup", targetNamespace = "http://xml.amadeus.com/TIPNRQ_12_4_1A")
        com.amadeus.xml.tipnrq_12_4_1a.FareInformativePricingWithoutPNR.ObFeeRequestGroup obFeeRequestGroup,
        @WebParam(name = "messageDetails", targetNamespace = "http://xml.amadeus.com/TIPNRR_12_4_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.tipnrr_12_4_1a.MessageActionDetailsTypeI> messageDetails0,
        @WebParam(name = "errorGroup", targetNamespace = "http://xml.amadeus.com/TIPNRR_12_4_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.tipnrr_12_4_1a.ErrorGroupType> errorGroup,
        @WebParam(name = "mainGroup", targetNamespace = "http://xml.amadeus.com/TIPNRR_12_4_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.tipnrr_12_4_1a.FareInformativePricingWithoutPNRReply.MainGroup> mainGroup,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param errorMessage
     * @param solutionFamily0
     * @param officeIdDetails0
     * @param travelFlightInfo
     * @param paxReference
     * @param officeIdDetails
     * @param link
     * @param feeDetails
     * @param replyStatus
     * @param security
     * @param ticketChangeInfo
     * @param numberOfUnit
     * @param taxInfo
     * @param combinationFareFamilies
     * @param fareFamilies
     * @param mnrGrp
     * @param passengerInfoGrp
     * @param amountInfoPerPax
     * @param value
     * @param itinerary
     * @param otherSolutions
     * @param valueSearch
     * @param globalInformation
     * @param familyInformation
     * @param warningInfo
     * @param feeOption
     * @param serviceFeesGrp
     * @param recommendation
     * @param companyIdText
     * @param solutionFamily
     * @param formOfPaymentByPassenger
     * @param flightIndex
     * @param amountInfoForAllPax
     * @param fareOptions
     * @param session
     * @param customerRef
     * @param priceToBeat
     * @param globalOptions
     * @param conversionRate
     */
    @WebMethod(operationName = "Fare_MasterPricerTravelBoardSearch", action = "http://webservices.amadeus.com/FMPTBQ_14_2_1A")
    @RequestWrapper(localName = "Fare_MasterPricerTravelBoardSearch", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A", className = "com.amadeus.xml.fmptbq_14_2_1a.FareMasterPricerTravelBoardSearch")
    @ResponseWrapper(localName = "Fare_MasterPricerTravelBoardSearchReply", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", className = "com.amadeus.xml.fmptbr_14_2_1a.FareMasterPricerTravelBoardSearchReply")
    public void fareMasterPricerTravelBoardSearch(
        @WebParam(name = "numberOfUnit", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A")
        NumberOfUnitsType numberOfUnit,
        @WebParam(name = "globalOptions", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A")
        AttributeType globalOptions,
        @WebParam(name = "paxReference", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A")
        List<TravellerReferenceInformationType> paxReference,
        @WebParam(name = "customerRef", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A")
        ConsumerReferenceInformationType customerRef,
        @WebParam(name = "formOfPaymentByPassenger", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A")
        List<FOPRepresentationType> formOfPaymentByPassenger,
        @WebParam(name = "solutionFamily", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A")
        List<com.amadeus.xml.fmptbq_14_2_1a.FareInformationType> solutionFamily,
        @WebParam(name = "passengerInfoGrp", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A")
        List<GroupPassengerDetailsType> passengerInfoGrp,
        @WebParam(name = "fareFamilies", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A")
        List<com.amadeus.xml.fmptbq_14_2_1a.FareMasterPricerTravelBoardSearch.FareFamilies> fareFamilies,
        @WebParam(name = "fareOptions", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A")
        com.amadeus.xml.fmptbq_14_2_1a.FareMasterPricerTravelBoardSearch.FareOptions fareOptions,
        @WebParam(name = "priceToBeat", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A")
        com.amadeus.xml.fmptbq_14_2_1a.MonetaryInformationType priceToBeat,
        @WebParam(name = "taxInfo", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A")
        List<TaxType> taxInfo,
        @WebParam(name = "travelFlightInfo", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A")
        TravelFlightInformationType165052S travelFlightInfo,
        @WebParam(name = "valueSearch", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A")
        List<com.amadeus.xml.fmptbq_14_2_1a.ValueSearchCriteriaType> valueSearch,
        @WebParam(name = "itinerary", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A")
        List<com.amadeus.xml.fmptbq_14_2_1a.FareMasterPricerTravelBoardSearch.Itinerary> itinerary,
        @WebParam(name = "ticketChangeInfo", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A")
        com.amadeus.xml.fmptbq_14_2_1a.FareMasterPricerTravelBoardSearch.TicketChangeInfo ticketChangeInfo,
        @WebParam(name = "combinationFareFamilies", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A")
        List<com.amadeus.xml.fmptbq_14_2_1a.FareMasterPricerTravelBoardSearch.CombinationFareFamilies> combinationFareFamilies,
        @WebParam(name = "feeOption", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A")
        List<com.amadeus.xml.fmptbq_14_2_1a.FareMasterPricerTravelBoardSearch.FeeOption> feeOption,
        @WebParam(name = "officeIdDetails", targetNamespace = "http://xml.amadeus.com/FMPTBQ_14_2_1A")
        List<com.amadeus.xml.fmptbq_14_2_1a.FareMasterPricerTravelBoardSearch.OfficeIdDetails> officeIdDetails,
        @WebParam(name = "replyStatus", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", mode = WebParam.Mode.OUT)
        Holder<StatusType> replyStatus,
        @WebParam(name = "errorMessage", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.fmptbr_14_2_1a.FareMasterPricerTravelBoardSearchReply.ErrorMessage> errorMessage,
        @WebParam(name = "conversionRate", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.fmptbr_14_2_1a.ConversionRateTypeI> conversionRate,
        @WebParam(name = "solutionFamily", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.fmptbr_14_2_1a.FareInformationType>> solutionFamily0,
        @WebParam(name = "familyInformation", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", mode = WebParam.Mode.OUT)
        Holder<List<FareFamilyType>> familyInformation,
        @WebParam(name = "amountInfoForAllPax", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.fmptbr_14_2_1a.FareMasterPricerTravelBoardSearchReply.AmountInfoForAllPax> amountInfoForAllPax,
        @WebParam(name = "amountInfoPerPax", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.fmptbr_14_2_1a.FareMasterPricerTravelBoardSearchReply.AmountInfoPerPax>> amountInfoPerPax,
        @WebParam(name = "feeDetails", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.fmptbr_14_2_1a.FareMasterPricerTravelBoardSearchReply.FeeDetails>> feeDetails,
        @WebParam(name = "companyIdText", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", mode = WebParam.Mode.OUT)
        Holder<List<CompanyIdentificationTextType>> companyIdText,
        @WebParam(name = "officeIdDetails", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.fmptbr_14_2_1a.FareMasterPricerTravelBoardSearchReply.OfficeIdDetails>> officeIdDetails0,
        @WebParam(name = "flightIndex", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.fmptbr_14_2_1a.FareMasterPricerTravelBoardSearchReply.FlightIndex>> flightIndex,
        @WebParam(name = "recommendation", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.fmptbr_14_2_1a.FareMasterPricerTravelBoardSearchReply.Recommendation>> recommendation,
        @WebParam(name = "otherSolutions", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.fmptbr_14_2_1a.FareMasterPricerTravelBoardSearchReply.OtherSolutions>> otherSolutions,
        @WebParam(name = "warningInfo", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.fmptbr_14_2_1a.FareMasterPricerTravelBoardSearchReply.WarningInfo>> warningInfo,
        @WebParam(name = "globalInformation", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.fmptbr_14_2_1a.FareMasterPricerTravelBoardSearchReply.GlobalInformation>> globalInformation,
        @WebParam(name = "serviceFeesGrp", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.fmptbr_14_2_1a.FareMasterPricerTravelBoardSearchReply.ServiceFeesGrp>> serviceFeesGrp,
        @WebParam(name = "value", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.fmptbr_14_2_1a.ValueSearchCriteriaType>> value,
        @WebParam(name = "mnrGrp", targetNamespace = "http://xml.amadeus.com/FMPTBR_14_2_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.fmptbr_14_2_1a.FareMasterPricerTravelBoardSearchReply.MnrGrp> mnrGrp,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param applicationError
     * @param frequentFlyerInformation
     * @param flightInformation
     * @param dateOverride
     * @param link
     * @param instantPricingOption
     * @param security
     * @param pnrLocatorData
     * @param fopInformation
     * @param fareList
     * @param bookingClassSelection
     * @param discountInformation
     * @param session
     * @param validatingCarrier
     * @param pricingFareBase
     * @param overrideInformation
     * @param currencyOverride
     * @param cityOverride
     * @param paxSegReference
     * @param openSegmentsInformation
     * @param carrierAgreements
     * @param pnrLocatorData0
     * @param taxDetails
     */
    @WebMethod(operationName = "Fare_PricePNRWithBookingClass", action = "http://webservices.amadeus.com/TPCBRQ_12_4_1A")
    @RequestWrapper(localName = "Fare_PricePNRWithBookingClass", targetNamespace = "http://xml.amadeus.com/TPCBRQ_12_4_1A", className = "com.amadeus.xml.tpcbrq_12_4_1a.FarePricePNRWithBookingClass")
    @ResponseWrapper(localName = "Fare_PricePNRWithBookingClassReply", targetNamespace = "http://xml.amadeus.com/TPCBRR_12_4_1A", className = "com.amadeus.xml.tpcbrr_12_4_1a.FarePricePNRWithBookingClassReply")
    public void farePricePNRWithBookingClass(
        @WebParam(name = "pnrLocatorData", targetNamespace = "http://xml.amadeus.com/TPCBRQ_12_4_1A")
        com.amadeus.xml.tpcbrq_12_4_1a.ReservationControlInformationTypeI pnrLocatorData,
        @WebParam(name = "paxSegReference", targetNamespace = "http://xml.amadeus.com/TPCBRQ_12_4_1A")
        ReferenceInformationTypeI94605S paxSegReference,
        @WebParam(name = "overrideInformation", targetNamespace = "http://xml.amadeus.com/TPCBRQ_12_4_1A")
        com.amadeus.xml.tpcbrq_12_4_1a.CodedAttributeType overrideInformation,
        @WebParam(name = "dateOverride", targetNamespace = "http://xml.amadeus.com/TPCBRQ_12_4_1A")
        com.amadeus.xml.tpcbrq_12_4_1a.StructuredDateTimeInformationType dateOverride,
        @WebParam(name = "validatingCarrier", targetNamespace = "http://xml.amadeus.com/TPCBRQ_12_4_1A")
        TransportIdentifierType validatingCarrier,
        @WebParam(name = "cityOverride", targetNamespace = "http://xml.amadeus.com/TPCBRQ_12_4_1A")
        PointOfSaleInformationTypeU cityOverride,
        @WebParam(name = "currencyOverride", targetNamespace = "http://xml.amadeus.com/TPCBRQ_12_4_1A")
        com.amadeus.xml.tpcbrq_12_4_1a.ConversionRateTypeI currencyOverride,
        @WebParam(name = "taxDetails", targetNamespace = "http://xml.amadeus.com/TPCBRQ_12_4_1A")
        List<DutyTaxFeeDetailsTypeU> taxDetails,
        @WebParam(name = "discountInformation", targetNamespace = "http://xml.amadeus.com/TPCBRQ_12_4_1A")
        List<com.amadeus.xml.tpcbrq_12_4_1a.FarePricePNRWithBookingClass.DiscountInformation> discountInformation,
        @WebParam(name = "pricingFareBase", targetNamespace = "http://xml.amadeus.com/TPCBRQ_12_4_1A")
        List<com.amadeus.xml.tpcbrq_12_4_1a.FarePricePNRWithBookingClass.PricingFareBase> pricingFareBase,
        @WebParam(name = "flightInformation", targetNamespace = "http://xml.amadeus.com/TPCBRQ_12_4_1A")
        List<com.amadeus.xml.tpcbrq_12_4_1a.FarePricePNRWithBookingClass.FlightInformation> flightInformation,
        @WebParam(name = "openSegmentsInformation", targetNamespace = "http://xml.amadeus.com/TPCBRQ_12_4_1A")
        List<com.amadeus.xml.tpcbrq_12_4_1a.FarePricePNRWithBookingClass.OpenSegmentsInformation> openSegmentsInformation,
        @WebParam(name = "bookingClassSelection", targetNamespace = "http://xml.amadeus.com/TPCBRQ_12_4_1A")
        List<com.amadeus.xml.tpcbrq_12_4_1a.FarePricePNRWithBookingClass.BookingClassSelection> bookingClassSelection,
        @WebParam(name = "fopInformation", targetNamespace = "http://xml.amadeus.com/TPCBRQ_12_4_1A")
        com.amadeus.xml.tpcbrq_12_4_1a.FarePricePNRWithBookingClass.FopInformation fopInformation,
        @WebParam(name = "carrierAgreements", targetNamespace = "http://xml.amadeus.com/TPCBRQ_12_4_1A")
        CommercialAgreementsTypeI carrierAgreements,
        @WebParam(name = "frequentFlyerInformation", targetNamespace = "http://xml.amadeus.com/TPCBRQ_12_4_1A")
        List<com.amadeus.xml.tpcbrq_12_4_1a.FarePricePNRWithBookingClass.FrequentFlyerInformation> frequentFlyerInformation,
        @WebParam(name = "instantPricingOption", targetNamespace = "http://xml.amadeus.com/TPCBRQ_12_4_1A")
        com.amadeus.xml.tpcbrq_12_4_1a.MonetaryInformationType instantPricingOption,
        @WebParam(name = "applicationError", targetNamespace = "http://xml.amadeus.com/TPCBRR_12_4_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.tpcbrr_12_4_1a.ErrorGroupType> applicationError,
        @WebParam(name = "pnrLocatorData", targetNamespace = "http://xml.amadeus.com/TPCBRR_12_4_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.tpcbrr_12_4_1a.ReservationControlInformationTypeI> pnrLocatorData0,
        @WebParam(name = "fareList", targetNamespace = "http://xml.amadeus.com/TPCBRR_12_4_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.tpcbrr_12_4_1a.FarePricePNRWithBookingClassReply.FareList>> fareList,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param generalErrorInfo
     * @param dataElementsMaster
     * @param offerGroup
     * @param link
     * @param pnrType
     * @param pnrHeader
     * @param travellerInfo
     * @param security
     * @param numberOfUnits
     * @param pnrHeaderTag
     * @param historyData
     * @param sbrUpdatorPosDetails
     * @param pricingRecordGroup
     * @param sbrCreationPosDetails
     * @param dataElementsMaster0
     * @param queueInformations
     * @param tstData
     * @param sbrPOSDetails
     * @param reservationInfo
     * @param freeFormText
     * @param travellerInfo0
     * @param originDestinationDetails
     * @param technicalData
     * @param segmentGroupingInfo
     * @param session
     * @param pnrActions
     * @param freetextData
     * @param originDestinationDetails0
     * @param securityInformation
     * @param dcsData
     */
    @WebMethod(operationName = "PNR_AddMultiElements", action = "http://webservices.amadeus.com/PNRADD_14_1_1A")
    @RequestWrapper(localName = "PNR_AddMultiElements", targetNamespace = "http://xml.amadeus.com/PNRADD_14_1_1A", className = "com.amadeus.xml.pnradd_14_1_1a.PNRAddMultiElements")
    @ResponseWrapper(localName = "PNR_Reply", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", className = "com.amadeus.xml.pnracc_14_1_1a.PNRReply")
    public void pnrAddMultiElements(
        @WebParam(name = "reservationInfo", targetNamespace = "http://xml.amadeus.com/PNRADD_14_1_1A")
        com.amadeus.xml.pnradd_14_1_1a.ReservationControlInformationTypeI reservationInfo,
        @WebParam(name = "pnrActions", targetNamespace = "http://xml.amadeus.com/PNRADD_14_1_1A")
        com.amadeus.xml.pnradd_14_1_1a.OptionalPNRActionsType pnrActions,
        @WebParam(name = "travellerInfo", targetNamespace = "http://xml.amadeus.com/PNRADD_14_1_1A")
        List<com.amadeus.xml.pnradd_14_1_1a.PNRAddMultiElements.TravellerInfo> travellerInfo,
        @WebParam(name = "originDestinationDetails", targetNamespace = "http://xml.amadeus.com/PNRADD_14_1_1A")
        List<com.amadeus.xml.pnradd_14_1_1a.PNRAddMultiElements.OriginDestinationDetails> originDestinationDetails,
        @WebParam(name = "dataElementsMaster", targetNamespace = "http://xml.amadeus.com/PNRADD_14_1_1A")
        com.amadeus.xml.pnradd_14_1_1a.PNRAddMultiElements.DataElementsMaster dataElementsMaster,
        @WebParam(name = "pnrHeader", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.PnrHeader>> pnrHeader,
        @WebParam(name = "securityInformation", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<ReservationSecurityInformationType156156S> securityInformation,
        @WebParam(name = "queueInformations", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<QueueType> queueInformations,
        @WebParam(name = "numberOfUnits", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<NumberOfUnitsTypeI> numberOfUnits,
        @WebParam(name = "generalErrorInfo", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.GeneralErrorInfo>> generalErrorInfo,
        @WebParam(name = "pnrType", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.CodedAttributeType> pnrType,
        @WebParam(name = "freetextData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<LongFreeTextType>> freetextData,
        @WebParam(name = "pnrHeaderTag", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<StatusType178422S> pnrHeaderTag,
        @WebParam(name = "freeFormText", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<InteractiveFreeTextTypeI132924S>> freeFormText,
        @WebParam(name = "historyData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<PnrHistoryDataType>> historyData,
        @WebParam(name = "sbrPOSDetails", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<POSGroupType> sbrPOSDetails,
        @WebParam(name = "sbrCreationPosDetails", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<POSGroupType> sbrCreationPosDetails,
        @WebParam(name = "sbrUpdatorPosDetails", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<POSGroupType> sbrUpdatorPosDetails,
        @WebParam(name = "technicalData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.TechnicalData> technicalData,
        @WebParam(name = "travellerInfo", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.TravellerInfo>> travellerInfo0,
        @WebParam(name = "originDestinationDetails", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.OriginDestinationDetails>> originDestinationDetails0,
        @WebParam(name = "segmentGroupingInfo", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<SegmentGroupingInformationType>> segmentGroupingInfo,
        @WebParam(name = "dataElementsMaster", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.DataElementsMaster> dataElementsMaster0,
        @WebParam(name = "tstData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.TstData>> tstData,
        @WebParam(name = "pricingRecordGroup", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.PricingRecordGroup> pricingRecordGroup,
        @WebParam(name = "dcsData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.DcsData> dcsData,
        @WebParam(name = "offerGroup", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.OfferGroup> offerGroup,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param generalErrorInfo
     * @param dataElementsMaster
     * @param offerGroup
     * @param link
     * @param pnrType
     * @param pnrHeader
     * @param travellerInfo
     * @param security
     * @param cancelElements
     * @param numberOfUnits
     * @param historyData
     * @param pnrHeaderTag
     * @param sbrUpdatorPosDetails
     * @param pricingRecordGroup
     * @param sbrCreationPosDetails
     * @param queueInformations
     * @param tstData
     * @param sbrPOSDetails
     * @param reservationInfo
     * @param freeFormText
     * @param originDestinationDetails
     * @param technicalData
     * @param segmentGroupingInfo
     * @param session
     * @param pnrActions
     * @param freetextData
     * @param securityInformation
     * @param dcsData
     */
    @WebMethod(operationName = "PNR_Cancel", action = "http://webservices.amadeus.com/PNRXCL_14_1_1A")
    @RequestWrapper(localName = "PNR_Cancel", targetNamespace = "http://xml.amadeus.com/PNRXCL_14_1_1A", className = "com.amadeus.xml.pnrxcl_14_1_1a.PNRCancel")
    @ResponseWrapper(localName = "PNR_Reply", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", className = "com.amadeus.xml.pnracc_14_1_1a.PNRReply")
    public void pnrCancel(
        @WebParam(name = "reservationInfo", targetNamespace = "http://xml.amadeus.com/PNRXCL_14_1_1A")
        com.amadeus.xml.pnrxcl_14_1_1a.ReservationControlInformationType reservationInfo,
        @WebParam(name = "pnrActions", targetNamespace = "http://xml.amadeus.com/PNRXCL_14_1_1A")
        com.amadeus.xml.pnrxcl_14_1_1a.OptionalPNRActionsType pnrActions,
        @WebParam(name = "cancelElements", targetNamespace = "http://xml.amadeus.com/PNRXCL_14_1_1A")
        List<CancelPNRElementType> cancelElements,
        @WebParam(name = "pnrHeader", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.PnrHeader>> pnrHeader,
        @WebParam(name = "securityInformation", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<ReservationSecurityInformationType156156S> securityInformation,
        @WebParam(name = "queueInformations", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<QueueType> queueInformations,
        @WebParam(name = "numberOfUnits", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<NumberOfUnitsTypeI> numberOfUnits,
        @WebParam(name = "generalErrorInfo", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.GeneralErrorInfo>> generalErrorInfo,
        @WebParam(name = "pnrType", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.CodedAttributeType> pnrType,
        @WebParam(name = "freetextData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<LongFreeTextType>> freetextData,
        @WebParam(name = "pnrHeaderTag", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<StatusType178422S> pnrHeaderTag,
        @WebParam(name = "freeFormText", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<InteractiveFreeTextTypeI132924S>> freeFormText,
        @WebParam(name = "historyData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<PnrHistoryDataType>> historyData,
        @WebParam(name = "sbrPOSDetails", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<POSGroupType> sbrPOSDetails,
        @WebParam(name = "sbrCreationPosDetails", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<POSGroupType> sbrCreationPosDetails,
        @WebParam(name = "sbrUpdatorPosDetails", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<POSGroupType> sbrUpdatorPosDetails,
        @WebParam(name = "technicalData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.TechnicalData> technicalData,
        @WebParam(name = "travellerInfo", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.TravellerInfo>> travellerInfo,
        @WebParam(name = "originDestinationDetails", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.OriginDestinationDetails>> originDestinationDetails,
        @WebParam(name = "segmentGroupingInfo", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<SegmentGroupingInformationType>> segmentGroupingInfo,
        @WebParam(name = "dataElementsMaster", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.DataElementsMaster> dataElementsMaster,
        @WebParam(name = "tstData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.TstData>> tstData,
        @WebParam(name = "pricingRecordGroup", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.PricingRecordGroup> pricingRecordGroup,
        @WebParam(name = "dcsData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.DcsData> dcsData,
        @WebParam(name = "offerGroup", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.OfferGroup> offerGroup,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param generalErrorInfo
     * @param dataElementsMaster
     * @param offerGroup
     * @param link
     * @param pnrType
     * @param pnrHeader
     * @param settings
     * @param travellerInfo
     * @param security
     * @param numberOfUnits
     * @param historyData
     * @param pnrHeaderTag
     * @param sbrUpdatorPosDetails
     * @param pricingRecordGroup
     * @param sbrCreationPosDetails
     * @param queueInformations
     * @param tstData
     * @param sbrPOSDetails
     * @param freeFormText
     * @param originDestinationDetails
     * @param retrievalFacts
     * @param technicalData
     * @param segmentGroupingInfo
     * @param session
     * @param freetextData
     * @param securityInformation
     * @param dcsData
     */
    @WebMethod(operationName = "PNR_Retrieve", action = "http://webservices.amadeus.com/PNRRET_14_1_1A")
    @RequestWrapper(localName = "PNR_Retrieve", targetNamespace = "http://xml.amadeus.com/PNRRET_14_1_1A", className = "com.amadeus.xml.pnrret_14_1_1a.PNRRetrieve")
    @ResponseWrapper(localName = "PNR_Reply", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", className = "com.amadeus.xml.pnracc_14_1_1a.PNRReply")
    public void pnrRetrieve(
        @WebParam(name = "settings", targetNamespace = "http://xml.amadeus.com/PNRRET_14_1_1A")
        PNRRetrieve.Settings settings,
        @WebParam(name = "retrievalFacts", targetNamespace = "http://xml.amadeus.com/PNRRET_14_1_1A")
        PNRRetrieve.RetrievalFacts retrievalFacts,
        @WebParam(name = "pnrHeader", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.PnrHeader>> pnrHeader,
        @WebParam(name = "securityInformation", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<ReservationSecurityInformationType156156S> securityInformation,
        @WebParam(name = "queueInformations", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<QueueType> queueInformations,
        @WebParam(name = "numberOfUnits", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<NumberOfUnitsTypeI> numberOfUnits,
        @WebParam(name = "generalErrorInfo", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.GeneralErrorInfo>> generalErrorInfo,
        @WebParam(name = "pnrType", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.CodedAttributeType> pnrType,
        @WebParam(name = "freetextData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<LongFreeTextType>> freetextData,
        @WebParam(name = "pnrHeaderTag", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<StatusType178422S> pnrHeaderTag,
        @WebParam(name = "freeFormText", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<InteractiveFreeTextTypeI132924S>> freeFormText,
        @WebParam(name = "historyData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<PnrHistoryDataType>> historyData,
        @WebParam(name = "sbrPOSDetails", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<POSGroupType> sbrPOSDetails,
        @WebParam(name = "sbrCreationPosDetails", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<POSGroupType> sbrCreationPosDetails,
        @WebParam(name = "sbrUpdatorPosDetails", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<POSGroupType> sbrUpdatorPosDetails,
        @WebParam(name = "technicalData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.TechnicalData> technicalData,
        @WebParam(name = "travellerInfo", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.TravellerInfo>> travellerInfo,
        @WebParam(name = "originDestinationDetails", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.OriginDestinationDetails>> originDestinationDetails,
        @WebParam(name = "segmentGroupingInfo", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<SegmentGroupingInformationType>> segmentGroupingInfo,
        @WebParam(name = "dataElementsMaster", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.DataElementsMaster> dataElementsMaster,
        @WebParam(name = "tstData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.TstData>> tstData,
        @WebParam(name = "pricingRecordGroup", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.PricingRecordGroup> pricingRecordGroup,
        @WebParam(name = "dcsData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.DcsData> dcsData,
        @WebParam(name = "offerGroup", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.OfferGroup> offerGroup,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param pnrRetrieve141
     * @param session
     * @param link
     * @param security
     * @return
     *     returns com.amadeus.xml.tnlres_00_1_1a.PNRList
     */
    @WebMethod(operationName = "PNR_Retrieve2", action = "http://webservices.amadeus.com/PNRRET_14_1_1A")
    @WebResult(name = "PNR_List", targetNamespace = "http://xml.amadeus.com/TNLRES_00_1_1A", partName = "PNR_List_0_1")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public PNRList pnrRetrieve2(
        @WebParam(name = "PNR_Retrieve", targetNamespace = "http://xml.amadeus.com/PNRRET_14_1_1A", partName = "PNR_Retrieve_14_1")
        PNRRetrieve pnrRetrieve141,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param generalErrorInfo
     * @param dataElementsMaster
     * @param offerGroup
     * @param link
     * @param pnrType
     * @param pnrHeader
     * @param travellerInfo
     * @param security
     * @param numberOfUnits
     * @param historyData
     * @param pnrHeaderTag
     * @param sbrUpdatorPosDetails
     * @param pricingRecordGroup
     * @param sbrCreationPosDetails
     * @param queueInformations
     * @param tstData
     * @param sbrPOSDetails
     * @param reservationInfo
     * @param freeFormText
     * @param splitDetails
     * @param originDestinationDetails
     * @param technicalData
     * @param segmentGroupingInfo
     * @param session
     * @param freetextData
     * @param securityInformation
     * @param dcsData
     */
    @WebMethod(operationName = "PNR_Split", action = "http://webservices.amadeus.com/PNRSPL_14_1_1A")
    @RequestWrapper(localName = "PNR_Split", targetNamespace = "http://xml.amadeus.com/PNRSPL_14_1_1A", className = "com.amadeus.xml.pnrspl_14_1_1a.PNRSplit")
    @ResponseWrapper(localName = "PNR_Reply", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", className = "com.amadeus.xml.pnracc_14_1_1a.PNRReply")
    public void pnrSplit(
        @WebParam(name = "reservationInfo", targetNamespace = "http://xml.amadeus.com/PNRSPL_14_1_1A")
        com.amadeus.xml.pnrspl_14_1_1a.ReservationControlInformationType reservationInfo,
        @WebParam(name = "splitDetails", targetNamespace = "http://xml.amadeus.com/PNRSPL_14_1_1A")
        SplitPNRType splitDetails,
        @WebParam(name = "pnrHeader", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.PnrHeader>> pnrHeader,
        @WebParam(name = "securityInformation", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<ReservationSecurityInformationType156156S> securityInformation,
        @WebParam(name = "queueInformations", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<QueueType> queueInformations,
        @WebParam(name = "numberOfUnits", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<NumberOfUnitsTypeI> numberOfUnits,
        @WebParam(name = "generalErrorInfo", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.GeneralErrorInfo>> generalErrorInfo,
        @WebParam(name = "pnrType", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.CodedAttributeType> pnrType,
        @WebParam(name = "freetextData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<LongFreeTextType>> freetextData,
        @WebParam(name = "pnrHeaderTag", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<StatusType178422S> pnrHeaderTag,
        @WebParam(name = "freeFormText", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<InteractiveFreeTextTypeI132924S>> freeFormText,
        @WebParam(name = "historyData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<PnrHistoryDataType>> historyData,
        @WebParam(name = "sbrPOSDetails", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<POSGroupType> sbrPOSDetails,
        @WebParam(name = "sbrCreationPosDetails", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<POSGroupType> sbrCreationPosDetails,
        @WebParam(name = "sbrUpdatorPosDetails", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<POSGroupType> sbrUpdatorPosDetails,
        @WebParam(name = "technicalData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.TechnicalData> technicalData,
        @WebParam(name = "travellerInfo", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.TravellerInfo>> travellerInfo,
        @WebParam(name = "originDestinationDetails", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.OriginDestinationDetails>> originDestinationDetails,
        @WebParam(name = "segmentGroupingInfo", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<SegmentGroupingInformationType>> segmentGroupingInfo,
        @WebParam(name = "dataElementsMaster", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.DataElementsMaster> dataElementsMaster,
        @WebParam(name = "tstData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.pnracc_14_1_1a.PNRReply.TstData>> tstData,
        @WebParam(name = "pricingRecordGroup", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.PricingRecordGroup> pricingRecordGroup,
        @WebParam(name = "dcsData", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.DcsData> dcsData,
        @WebParam(name = "offerGroup", targetNamespace = "http://xml.amadeus.com/PNRACC_14_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.pnracc_14_1_1a.PNRReply.OfferGroup> offerGroup,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param session
     * @param processStatus
     * @param link
     * @param conversationClt
     * @param security
     * @param errorSection
     */
    @WebMethod(operationName = "Security_SignOut", action = "http://webservices.amadeus.com/VLSSOQ_04_1_1A")
    @RequestWrapper(localName = "Security_SignOut", targetNamespace = "http://xml.amadeus.com/VLSSOQ_04_1_1A", className = "com.amadeus.xml.vlssoq_04_1_1a.SecuritySignOut")
    @ResponseWrapper(localName = "Security_SignOutReply", targetNamespace = "http://xml.amadeus.com/VLSSOR_04_1_1A", className = "com.amadeus.xml.vlssor_04_1_1a.SecuritySignOutReply")
    public void securitySignOut(
        @WebParam(name = "conversationClt", targetNamespace = "http://xml.amadeus.com/VLSSOQ_04_1_1A")
        ConversationIDType conversationClt,
        @WebParam(name = "errorSection", targetNamespace = "http://xml.amadeus.com/VLSSOR_04_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.vlssor_04_1_1a.SecuritySignOutReply.ErrorSection> errorSection,
        @WebParam(name = "processStatus", targetNamespace = "http://xml.amadeus.com/VLSSOR_04_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.vlssor_04_1_1a.ResponseAnalysisDetailsType> processStatus,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

    /**
     * 
     * @param applicationError
     * @param session
     * @param link
     * @param psaList
     * @param security
     * @param tstList
     * @param pnrLocatorData
     * @param pnrLocatorData0
     */
    @WebMethod(operationName = "Ticket_CreateTSTFromPricing", action = "http://webservices.amadeus.com/TAUTCQ_04_1_1A")
    @RequestWrapper(localName = "Ticket_CreateTSTFromPricing", targetNamespace = "http://xml.amadeus.com/TAUTCQ_04_1_1A", className = "com.amadeus.xml.tautcq_04_1_1a.TicketCreateTSTFromPricing")
    @ResponseWrapper(localName = "Ticket_CreateTSTFromPricingReply", targetNamespace = "http://xml.amadeus.com/TAUTCR_04_1_1A", className = "com.amadeus.xml.tautcr_04_1_1a.TicketCreateTSTFromPricingReply")
    public void ticketCreateTSTFromPricing(
        @WebParam(name = "pnrLocatorData", targetNamespace = "http://xml.amadeus.com/TAUTCQ_04_1_1A")
        com.amadeus.xml.tautcq_04_1_1a.ReservationControlInformationTypeI pnrLocatorData,
        @WebParam(name = "psaList", targetNamespace = "http://xml.amadeus.com/TAUTCQ_04_1_1A")
        List<com.amadeus.xml.tautcq_04_1_1a.TicketCreateTSTFromPricing.PsaList> psaList,
        @WebParam(name = "applicationError", targetNamespace = "http://xml.amadeus.com/TAUTCR_04_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.tautcr_04_1_1a.TicketCreateTSTFromPricingReply.ApplicationError> applicationError,
        @WebParam(name = "pnrLocatorData", targetNamespace = "http://xml.amadeus.com/TAUTCR_04_1_1A", mode = WebParam.Mode.OUT)
        Holder<com.amadeus.xml.tautcr_04_1_1a.ReservationControlInformationTypeI> pnrLocatorData0,
        @WebParam(name = "tstList", targetNamespace = "http://xml.amadeus.com/TAUTCR_04_1_1A", mode = WebParam.Mode.OUT)
        Holder<List<com.amadeus.xml.tautcr_04_1_1a.TicketCreateTSTFromPricingReply.TstList>> tstList,
        @WebParam(name = "Session", targetNamespace = "http://xml.amadeus.com/2010/06/Session_v3", header = true, mode = WebParam.Mode.INOUT, partName = "session")
        Holder<Session> session,
        @WebParam(name = "TransactionFlowLink", targetNamespace = "http://wsdl.amadeus.com/2010/06/ws/Link_v1", header = true, mode = WebParam.Mode.INOUT, partName = "link")
        Holder<TransactionFlowLinkType> link,
        @WebParam(name = "AMA_SecurityHostedUser", targetNamespace = "http://xml.amadeus.com/2010/06/Security_v1", header = true, partName = "security")
        AMASecurityHostedUser security);

}
